PalLocalPlanner:

  # main params
  max_vel_x : &max_vel_x 0.8
  max_rot_vel: !degrees 60.0
  acc_lim_x    : 0.6
  acc_lim_theta: !degrees 180.0
  xy_goal_tolerance : 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  # mcc params
  point_b_sfl        : 0.26
  decay              : 0.85
  max_dist_plan_ahead: 2.0
  min_dist_plan_ahead: 0.3
  dist_to_final_speed: 1.0
  allow_backwards    : false

  # oa params
  robot_width             : 0.54
  target_direction_infl   : 0.3
  wheel_orientation_infl  : 0.0
  previous_direction_infl : 0.3
  max_threshold           : 1.8
  security_dist           : 0.025
