footprint: [[0.26, 0.26], [-0.26, 0.26], [-0.26, -0.26], [0.26, -0.26]]
footprint_padding: 0.00002

robot_base_frame: base_footprint
update_frequency: 9.0
publish_frequency: 9.0
transform_tolerance: 1.0


static:
    map_topic: /map
    subscribe_to_updates: true

inflation_radius: 1.75
cost_scaling_factor: 2.58


obstacles_layer:
    origin_z: 0.0
    z_resolution: 0.03
    z_voxels: 10
    publish_voxel_map: false
    obstacle_range: 4.5
    raytrace_range: 5.0
    observation_sources: depth
    depth: {data_type: PointCloud2,topic: /kinect2/qhd/points,marking: true,clearing: true,enabled: true,inf_is_valid: true}
    observation_sources: laser
    laser: {sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

subscribe_to_updates: true
#always_send_full_costmap: true

#inflation:
#    cost_scaling_factor: 0.33
#    inflation_radius: 1.0 


