# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.2

  update_frequency : 5.0
  publish_frequency: 2.0

  static_map    : false
  rolling_window: true
  width         : 5.0
  height        : 5.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded on a separate file

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 6
      obstacle_range: 5
      min_obstacle_height: -0.1
      max_obstacle_height: 0.4

  obstacle_vo_layer:
    enabled: true
    observation_sources: vo_cloud
    combination_method: 1

    vo_cloud:
      sensor_frame: map
      data_type: PointCloud
      topic: vo_cloud
      expected_update_rate: 12.0
      observation_persistence: 0.0
      marking: true
      clearing: false
      raytrace_range: 1.0
      obstacle_range: 100.0
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0

  inflation_layer:
    enabled            : false
    inflation_radius   : 0.55
    cost_scaling_factor: 5.0
